"""Add columns to tables

Revision ID: 3a90964f3dca
Revises: 755fd8b6fcc5
Create Date: 2023-06-06 08:10:14.056921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a90964f3dca'
down_revision = '755fd8b6fcc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.drop_column('clusters', 'createDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('createDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('clusters', 'create_date')
    # ### end Alembic commands ###
