"""Add columns to tables

Revision ID: 72ea64d75cb5
Revises: fbce3d11001c
Create Date: 2023-06-06 13:42:34.136215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ea64d75cb5'
down_revision = 'fbce3d11001c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('cluster_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'cluster_num')
    # ### end Alembic commands ###
