"""Add columns to tables

Revision ID: 755fd8b6fcc5
Revises: f5d4cc8dc26c
Create Date: 2023-06-06 07:50:42.505039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755fd8b6fcc5'
down_revision = 'f5d4cc8dc26c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('createDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'createDate')
    # ### end Alembic commands ###
