"""Add columns to tables

Revision ID: f5d4cc8dc26c
Revises: 7c7de77458dc
Create Date: 2023-06-06 07:21:43.129381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d4cc8dc26c'
down_revision = '7c7de77458dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'keywords')
    # ### end Alembic commands ###
