"""Add columns to tables

Revision ID: fbce3d11001c
Revises: 3a90964f3dca
Create Date: 2023-06-06 09:36:59.983806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbce3d11001c'
down_revision = '3a90964f3dca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
